apiVersion: v1
kind: Service
metadata:
  name: taxi2
  annotations:
    link.argocd.argoproj.io/external-link: http://google.ca
  labels:
    app.kubernetes.io/name: taxi2
    app.kubernetes.io/version: 0.0.1
spec:
  selector:
    app.kubernetes.io/name: taxi2
    app.kubernetes.io/version: 0.0.1
  ports:
  - port: 8080
    protocol: TCP
    name: http
